---
- name: java done
  hosts: domain
  tasks:
    - name: install nodejs,python3 and python2
      tags: always
      win_chocolatey:
        name: 
          - nodejs-lts
          - python3
          - python2
        state: present

    #- name: Install "coffee-script" node.js package globally.
     # delegate_to: localhost
      #community.general.npm:
       # name: coffee-script
        #global: yes

    - name: Install angular
      #tags: angular,cli    #tags utilization
      script: angular.ps1 
      register: out

    - debug: var=out.stdout_lines
     
    - name: Add ng to path
      win_path:
        elements:
          - 'C:\Users\admin\AppData\Roaming\npm'
      