---
- name: java done
  hosts: domain
  tasks:
    - name: install nodejs
      win_chocolatey:
        name: nodejs-lts
        state: present

    - name: install python3
      win_chocolatey:
        name: python3
        state: present

    - name: install python2
      win_chocolatey:
        name: python2
        state: present
    #- name: Install "coffee-script" node.js package globally.
     # delegate_to: localhost
      #community.general.npm:
       # name: coffee-script
        #global: yes

    - name: Install angular
      script: angular.ps1 
      register: out

    - debug: var=out.stdout_lines
     
    - name: Add ng to path
      win_path:
        elements:
          - 'C:\Users\admin\AppData\Roaming\npm'
      