---
- name: java done
  hosts: domain
  tasks:
    - name: Install Java
      win_chocolatey:
        name: jdk8
        state: present
        #version: '8.0'

  #  - name: Set Java_home
  #    win_environment:
  #      state: present
  #      name: JAVA_HOME
  #      value: 'c:\program files\java\jdk1.8.0_162'
  #      level: machine

  #  - name: Add Java to path
  #    win_path:
  #      elements:
  #        - 'c:\program files\java\jdk8.0_162\bin'
