- name: Install exe or msi and use a file version for the installation check
  ansible.windows.win_package:
    path: \\192.168.91.155\tools\Setup_x64Bit\Sep64.msi #or network path
  #  creates_path: C:\Program Files\Firefox\Firefox.exe
   # creates_version: 16.04
    state: present
 #Run installer from mounted ISO, then unmount
- name: Ensure an ISO is mounted
  community.windows.win_disk_image:
    image_path: \\192.168.0.117\Tools\Software\Tools\MS Office\Office 2016\Office 2016 x64 bit\SW_DVD5_Office_Professional_Plus_2016_64Bit_English_MLF_X20-42432.ISO
    state: present
  register: disk_image_out

- name: Run installer from mounted ISO
  ansible.windows.win_package:
    path: '{{ disk_image_out.mount_paths[0] }}setup\setup.exe'
    #product_id: 35a4e767-0161-46b0-979f-e61f282fee21
    state: present

- name: Unmount ISO
  community.windows.win_disk_image:
    image_path: \\192.168.0.117\Tools\Software\Tools\MS Office\Office 2016\Office 2016 x64 bit\SW_DVD5_Office_Professional_Plus_2016_64Bit_English_MLF_X20-42432.ISO
    state: absent