- name: Install exe or msi and // epson
  ansible.windows.win_package:
    path: C:\Users\admin\Desktop\tools\epson16189.exe #or network path
  #  creates_path: C:\Program Files\Firefox\Firefox.exe
   # creates_version: 16.04
    state: present
  notify: reboot host if required
  
- name: Install exe or msi and // symantec
  ansible.windows.win_package:
    path: C:\Users\admin\Desktop\tools\Setup_x64Bit\Sep64.msi #or network path
  #  creates_path: C:\Program Files\Firefox\Firefox.exe
   # creates_version: 16.04
    state: present
  notify: reboot host if required


 #Run installer from mounted ISO, then unmount
- name: Ensure an ISO is mounted
  community.windows.win_disk_image:
    image_path: C:\Users\admin\Desktop\tools\MS_Project_2016\SW_DVD5_Project_Pro_2016_64Bit_English_MLF_X20-42683.ISO
    state: present
  register: disk_image_out

- name: Run installer from mounted ISO
  ansible.windows.win_package:
    path: '{{ disk_image_out.mount_paths[0] }}setup.exe'
    #product_id: 35a4e767-0161-46b0-979f-e61f282fee21
    state: present

- name: Unmount ISO
  community.windows.win_disk_image:
    image_path: C:\Users\admin\Desktop\tools\MS_Project_2016\SW_DVD5_Project_Pro_2016_64Bit_English_MLF_X20-42683.ISO
    state: absent

- name: Ensure an ISO is mounted
  community.windows.win_disk_image:
    image_path: C:\Users\admin\Desktop\tools\MS_Visio_Pro_2016_x64_Bit_(En)\SW_DVD5_Visio_Pro_2016_64Bit_English_MLF_X20-42764.ISO
    state: present
  register: disk_image_out

- name: Run installer from mounted ISO
  ansible.windows.win_package:
    path: '{{ disk_image_out.mount_paths[0] }}setup.exe'
    #product_id: 35a4e767-0161-46b0-979f-e61f282fee21
    state: present

- name: Unmount ISO
  community.windows.win_disk_image:
    image_path: C:\Users\admin\Desktop\tools\MS_Visio_Pro_2016_x64_Bit_(En)\SW_DVD5_Visio_Pro_2016_64Bit_English_MLF_X20-42764.ISO
    state: absent

#- name: Install office
 # ansible.windows.win_package:
  #  path: C:\Users\admin\Desktop\tools\Office_Professional_Plus_2016\setup.exe
   # state: present    
