- name: Change the hostname to sample-hostname
  ansible.windows.win_hostname:
    name: Test-LAP
  notify: reboot host if required

- name: Add a machine to domain
  win_domain_membership:
    dns_domain_name: 
    hostname: Test-LAP
    domain_admin_user: 
    domain_admin_password: 
    #domain_ou_path: 
    state: domain
  notify: reboot host if required
  
- name: Add a domain user to domain
  win_group_membership:
    name: Remote Desktop Users
    members:
    - INTEG-OBJECTS\TestUser
    state: present
  notify: reboot host if required
  