- name: Change the hostname to sample-hostname
  ansible.windows.win_hostname:
    name: sample-PC
  notify: reboot host if required

- name: Add a machine to domain
  win_domain_membership:
    dns_domain_name: INTEG-OBJECTS.LOCAL
    hostname: sample-PC
    domain_admin_user: testguy@integ-objects.local
    domain_admin_password:  124dee4d54f
    domain_ou_path: "OU=Windows,OU=Servers,DC=IO-DELL-SVR10,DC=INTEG-OBJECTS.LOCAL,DC=IO-DELL-SVR10.INTEG-OBJECTS.LOCAL"
    state: domain
  notify: reboot host if required
  
- name: Add a domain user to domain
  win_group_membership:
    name: Remote Desktop Users
    members:
    - INTEG-OBJECTS\TestUser
    state: present
  notify: reboot host if required
  