- name: add security layer
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: SecurityLayer
    data: 2
    type: dword        

- name: add Min Encryption Level 1
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: MinEncryptionLevel
    data: 4
    type: dword

- name: add Min Encryption Level 2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows NT\Terminal Services
    name: MinEncryptionLevel
    data: 4
    type: dword

- name: add Feature Settings Override
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
    name: FeatureSettingsOverrideMask
    data: 0x00000003
    type: dword  

- name: add Feature Settings Override
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
    name: FeatureSettingsOverride
    data: 0x00002048 
    type: dword

- name: add Min Vm Version For Cpu Based Mitigations
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization
    name: MinVmVersionForCpuBasedMitigations
    data: 1.0 
    type: string    

- name: disable SSL 3.0
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0
    name: Server
    data: 00000000 
    type: dword                

- name: update internet explorer regedit 1
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_ALLOW_USER32_EXCEPTION_HANDLER_HARDENING
    name: iexplore.exe
    data: 00000001 
    type: dword   

- name: update internet explorer regedit 2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_ENABLE_PRINT_INFO_DISCLOSURE_FIX
    name: iexplore.exe
    data: 00000001 
    type: dword  

- name: update internet explorer regedit 3
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_ALLOW_USER32_EXCEPTION_HANDLER_HARDENING
    name: iexplore.exe
    data: 00000001 
    type: dword  

- name: update internet explorer regedit 4
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\WOW6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_ENABLE_PRINT_INFO_DISCLOSURE_FIX
    name: iexplore.exe
    data: 00000001 
    type: dword  

- name: update Diffie_Hellman keys regedit
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms
    name: Diffie-Hellman
    data: 00000000
    type: dword  

- name: add LM Compatibility Level keys regedit
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\LSA
    name: LMCompatibilityLevel
    data: 5
    type: dword     

- name: add Ciphers keys regedit 1
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\Schannel\Ciphers\RC4 40/128
    name: Enabled
    data: 0
    type: dword      

- name: add Ciphers keys regedit 2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\Schannel\Ciphers\RC4 56/128
    name: Enabled
    data: 0
    type: dword

- name: disable SSL_SVR_3
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server
    name: Enabled
    data: 00000000
    type: dword

- name: disable SSL_SVR_3
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server
    name: DisabledByDefault
    data: 00000001
    type: dword   

- name: disable SSL_CL_3
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client
    name: Enabled
    data: 00000000
    type: dword

- name: disable SSL_CL_3
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client
    name: DisabledByDefault
    data: 00000001
    type: dword      

- name: disable SSL_SVR_2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server
    name: Enabled
    data: 00000000
    type: dword

- name: disable SSL_SVR_2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server
    name: DisabledByDefault
    data: 00000001
    type: dword   

- name: disable SSL_CL_2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client
    name: Enabled
    data: 00000000
    type: dword
    
- name: disable SSL_CL_2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client
    name: DisabledByDefault
    data: 00000001
    type: dword

- name: disable TLS_1_SVR
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
    name: Enabled
    data: 00000000
    type: dword

- name: disable TLS_1_SVR
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
    name: DisabledByDefault
    data: 00000001
    type: dword   

- name: disable TLS_1_CL
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
    name: Enabled
    data: 00000000
    type: dword
    
- name: disable TLS_1_CL
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
    name: DisabledByDefault
    data: 00000001
    type: dword 

- name: enable TLS_2_SVR
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
    name: Enabled
    data: 00000001
    type: dword

- name: enable TLS_2_SVR
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
    name: DisabledByDefault
    data: 00000000
    type: dword   

- name: enable TLS_2_CL
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
    name: Enabled
    data: 00000001
    type: dword
    
- name: enable TLS_2_CL
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
    name: DisabledByDefault
    data: 00000000
    type: dword     

- name: enable TLS_3_SVR
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
    name: Enabled
    data: 00000001
    type: dword

- name: enable TLS_3_SVR
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
    name: DisabledByDefault
    data: 00000000
    type: dword   

- name: enable TLS_3_CL
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
    name: Enabled
    data: 00000001
    type: dword
    
- name: enable TLS_3_CL
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
    name: DisabledByDefault
    data: 00000000
    type: dword           