- name: add security layer
  ansible.windows.win_regedit:
    path: "{{SecurityLayer}}"
    name: SecurityLayer
    data: 2
    type: dword        

- name: add Min Encryption Level
  ansible.windows.win_regedit:
    path: "{{SecurityLayer}}"
    name: MinEncryptionLevel
    data: 4
    type: dword

- name: add Feature Settings Override
  ansible.windows.win_regedit:
    path: "{{FeatureSettingsOverride}}"
    name: FeatureSettingsOverrideMask
    data: 0x00000003
    type: dword  

- name: add Feature Settings Override
  ansible.windows.win_regedit:
    path: "{{FeatureSettingsOverride}}"
    name: FeatureSettingsOverride
    data: 0x00002048 
    type: dword

- name: disable SSL 3.0
  ansible.windows.win_regedit:
    path: "{{Server}}"
    name: Server
    data: 00000000 
    type: dword                

- name: update internet explorer regedit 1
  ansible.windows.win_regedit:
    path: "{{iexplorer}}"
    name: iexplore.exe
    data: 00000001 
    type: dword   

- name: update internet explorer regedit 2
  ansible.windows.win_regedit:
    path: "{{iexplore}}"
    name: iexplore.exe
    data: 00000001 
    type: dword  

- name: update internet explorer regedit 3
  ansible.windows.win_regedit:
    path: "{{internet_exp}}"
    name: iexplore.exe
    data: 00000001 
    type: dword  

- name: update internet explorer regedit 4
  ansible.windows.win_regedit:
    path: "{{intenret}}"
    name: iexplore.exe
    data: 00000001 
    type: dword  

- name: update Diffie_Hellman keys regedit
  ansible.windows.win_regedit:
    path: "{{Diffie_Hellman}}"
    name: Diffie-Hellman
    data: 00000000
    type: dword  