---
- name: check installed software
  hosts: domain
  tasks:
    - 
      name: run script
      script: Get-InstalledApps.ps1 > C:\Users\admin\Desktop\ansible.txt
      register: out

    - name: copy file to master
      fetch: src=C:\\Users\\admin\\Desktop\\ansible.txt dest=/home/ansible/ flat=yes