---

SecurityLayer: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\SecurityLayer
#: \HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\MinEncryptionLevel

FeatureSettingsOverride: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\FeatureSettingsOverrideMask
#: SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\FeatureSettingsOverride

Server: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server

iexplorer: HKLM:\SOFTWARE\Microsoft\Internet Explorer\MAIN \FeatureControl \FEATURE_ALLOW_USER32_EXCEPTION_HANDLER_HARDENING \iexplore.exe

iexplore: HKLM:\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\ FEATURE_ENABLE_PRINT_INFO_DISCLOSURE_FIX\iexplore.exe

internet_exp: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl \FEATURE_ALLOW_USER32_EXCEPTION_HANDLER_HARDENING\iexplore.exe

intenret: HKLM:\SOFTWARE\WOW6432Node\Microsoft\Internet Explorer\Main\FeatureControl\ FEATURE_ENABLE_PRINT_INFO_DISCLOSURE_FIX\iexplore.exe

Diffie-Hellman: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman


