---
- name: Add or update registry 
  hosts: domain
  tasks:
    - name: update chrome regedit value
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Google\Chrome
        name: RendererCodeIntegrityEnabled
        data: 0x00000000
        type: dword
