---
- name: Add or update registry 
  hosts: newpc
  tasks:
    - name: update chrome regedit value
      ansible.windows.win_regedit:
        path: "{{regeditChrome}}"
        name: RendererCodeIntegrityEnabled
        data: 0x00000000
        type: dword

#- name: Copy tomcat config copy example
 # win_copy:
  #  src: log4j.xml
   # dest: '{{tc_home}}\lib\log4j.xml'